<?php
/**
 * Implement hook_menu().
 */
function dexp_menu() {
  $items = array();
  $items['admin/drupalexp'] = array(
      'title' => t('DrupalExp'),
      'page callback' => 'dexp_global_settings',
      'access arguments' => array('administer dexp modules'),
      'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

function dexp_global_settings() {
  $result = db_query("SELECT mlid FROM {menu_links} AS l WHERE l.link_path LIKE 'admin/drupalexp/%'");

  $html = '<div class="admin-panel"><ul class="admin-list">';
  while ($row = $result->fetchObject()) {
    $link = menu_link_load($row->mlid);
    $html .= '<h3>' . $link['title'] . '</h3><li>' . l($link['link_title'], $link['link_path']) . '<div class="description">' . $link['description'] . '</div></li>';
  }
  $html .="</ul></div>";
  return $html;
}

function dexp_permission()
{
  return array(
    'administer dexp modules' => array(
      'title' => t('Administer Dexp Modules'),
      'description' => t('Administer Dexp Modules.')
    )
  );
}